// Code generated by finevines redirects.GenerateMiddleware. DO NOT EDIT BY
// HAND â€” edit internal/redirects/middleware.ts.tmpl and regenerate instead.
//
// Bunny.net Edge Scripting middleware for the finevines.com old-site ->
// new-site 301 redirect map (plan Task 20, design spec Â§7).
//
// DESIGN DECISION â€” fetch-from-storage, not an inlined const map:
//
// The old finevines.com site has 51,511 discovered URLs, which serialize
// to roughly 5.4MB of JSON. Bunny's confirmed Edge Scripting limits
// (docs.bunny.net/scripting/limits) are:
//   - Script size:   10 MB
//   - Startup time: 500 ms (maximum time to evaluate the script's
//     module-level/top-level code, before it can serve a single request)
//
// Inlining all 51,511 entries as a `Record<string, string>` object literal
// would fit under the 10MB script-size cap today, but two things make it
// the wrong choice at this scale:
//
//  1. It leaves almost no headroom. The map only grows as more legacy
//     URLs are found (manual overrides, future crawls) â€” there is no
//     mechanism to shrink it back down, and a script that fails to
//     deploy because it silently crossed 10MB takes the WHOLE pull
//     zone's middleware down with it (this script wraps every request
//     to the zone, not just the URLs being redirected).
//  2. Far more decisive: V8 has to parse and evaluate that literal at
//     module scope on every cold isolate start, and Bunny enforces a
//     hard 500ms startup budget. A 5+MB object literal with 51k
//     properties is a real, direct risk of blowing that budget â€” and
//     since this script gates ALL origin traffic for the pull zone
//     (design, not just redirects), a startup-time violation would
//     degrade or break ordinary site requests, not just SEO redirects.
//
// So this script stays small and FIXED regardless of map size: it fetches
// redirects.json (deployed as an ordinary site asset, same as any other
// dist/ file) lazily on the FIRST request an isolate serves â€” not at
// module scope, so it never counts against the startup-time budget â€”
// parses it into a Map once, and reuses that Map for every subsequent
// request the isolate handles. A fetch failure fails open: the isolate
// falls back to an empty map, which makes every request pass through to
// origin unchanged. The site is never broken by a redirects-map problem.
//
// REENTRY GUARD: loadRedirects() fetches REDIRECT_MAP_URL through this
// SAME pull zone (it's just the site's own /redirects.json). Bunny's
// reentry behavior for an edge script's own subrequests isn't documented
// either way, but IF that subrequest is ever routed back through this same
// middleware on the same isolate while the parent call's redirectsPromise
// is still pending, awaiting it there would wait on a promise that can
// only resolve once that very (nested) request finishes â€” a circular
// deadlock with no timeout, no error, and no reset of redirectsPromise, so
// every subsequent request on the isolate hangs forever. onOriginRequest
// below checks the request path against the map's own path FIRST, before
// ever calling loadRedirects(), so the cycle is broken unconditionally â€”
// insurance against unconfirmed platform behavior, not a response to an
// observed bug.
//
// generator note: this file is a Go text/template â€” the only variable
// piece is the redirects.json URL below, so output is fully deterministic
// for a given input (important since the rendered file is committed to
// the repo for reproducibility / as the manual-dashboard-paste fallback).

import * as BunnySDK from "@bunny.net/edgescript-sdk";

// REDIRECT_MAP_URL points at the deployed redirects.json (the same file
// internal/redirects.Save writes and internal/deploy uploads as an
// ordinary site asset) â€” NOT baked into this script, so a redirects.json
// refresh never requires touching or redeploying this file.
const REDIRECT_MAP_URL = "https://finevines-biz.b-cdn.net/redirects.json";

// MAP_PATH is REDIRECT_MAP_URL's path component, computed once at module
// scope so the reentry guard in onOriginRequest (see REENTRY GUARD above)
// is a cheap per-request string comparison, not a URL parse.
const MAP_PATH = new URL(REDIRECT_MAP_URL).pathname;

// redirectsPromise memoizes the in-flight/completed fetch+parse of
// REDIRECT_MAP_URL for the lifetime of this isolate. Concurrent requests
// that arrive before the first fetch resolves all await the SAME promise
// (no thundering herd of duplicate fetches per isolate).
let redirectsPromise: Promise<Map<string, string>> | null = null;

async function loadRedirects(): Promise<Map<string, string>> {
  if (redirectsPromise) {
    return redirectsPromise;
  }

  redirectsPromise = (async () => {
    try {
      const res = await fetch(REDIRECT_MAP_URL);
      if (!res.ok) {
        throw new Error(`fetch ${REDIRECT_MAP_URL}: status ${res.status}`);
      }
      const data = (await res.json()) as Record<string, string>;
      return new Map(Object.entries(data));
    } catch (err) {
      // Fail open, never break the site: log and hand back an empty map,
      // which makes every lookup below miss and pass through to origin.
      console.error("finevines redirects: failed to load", REDIRECT_MAP_URL, err);
      // Don't cache the failure â€” the next request gets to retry the
      // fetch instead of being stuck with an empty map for the isolate's
      // whole lifetime.
      redirectsPromise = null;
      return new Map<string, string>();
    }
  })();

  return redirectsPromise;
}

BunnySDK.net.http
  // `url` here is only used by Bunny during local `deno run` development
  // (docs.bunny.net/scripting/middleware/overview) â€” in production the
  // Pull Zone's own configured origin is used instead, so this is a
  // reasonable stand-in rather than a value this script depends on.
  .servePullZone({ url: "https://finevines.biz" })
  .onOriginRequest(async (ctx: { request: Request }) => {
    const url = new URL(ctx.request.url);

    // Reentry guard (see REENTRY GUARD above) â€” must run BEFORE
    // loadRedirects() so the map's own self-fetch can never nest into
    // this handler while a parent call is still awaiting the same
    // in-flight redirectsPromise.
    if (url.pathname === MAP_PATH) {
      return ctx.request;
    }

    const redirects = await loadRedirects();

    const withQuery = url.pathname + url.search;

    // Try pathname+query first (the map's keys carry query strings when
    // the old URL had one), then fall back to pathname alone.
    const target = redirects.get(withQuery) ?? redirects.get(url.pathname);

    // Never 301 a URL to itself: MapURLs already drops identity pairs at
    // generation time, but this map is fetched at runtime and could be
    // stale or hand-edited â€” a self-target here would be an infinite
    // redirect loop on a live page, so guard again at the point of use.
    if (target && target !== withQuery && target !== url.pathname) {
      return new Response(null, {
        status: 301,
        headers: { Location: target },
      });
    }

    // Miss: pass the request through to origin unchanged.
    return ctx.request;
  });
