import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

// What is actually true about assets/img/wines/:
//
//   - Real bottle PHOTOGRAPHS (.jpg) live here and are committed.
//   - internal/enrich.writeImageFile also writes a generated <slug>.svg here
//     for every wine it could not find a photograph for — 1,360 of them right
//     now. Those are gitignored build artifacts (.gitignore:
//     `assets/img/wines/*.svg`), regenerated by every `finevines enrich`, and
//     they are the placeholders the site serves.
//   - The 33 hand-authored, invented-label SVGs that used to be TRACKED here
//     were deleted on 2026-08-09. Nothing referenced them.
//
// So "is there an .svg in this directory?" is not the invariant — after any
// local enrich there are over a thousand, legitimately. The invariant is that
// none of them is tracked: a tracked .svg is either the retired invented
// artwork restored from history, or a generated artifact committed by mistake
// and thereafter frozen while enrich's output moves on.
//
// git ls-files is what asks that question. It also makes these real CI
// regression guards rather than assertions about whoever's working tree.

// stdio: stderr piped, not inherited — git's diagnostics would otherwise land
// in the middle of the TAP stream.
const gitLsFiles = (pathspec) =>
  execFileSync('git', ['ls-files', '-z', '--', pathspec], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
    .split('\0')
    .filter(Boolean)

test('no SVG under assets/img/wines is tracked', () => {
  const tracked = gitLsFiles('assets/img/wines/*.svg')
  assert.deepEqual(
    tracked,
    [],
    `${tracked.length} tracked SVGs under assets/img/wines — enrich's placeholders are ` +
      `gitignored build artifacts and must stay untracked, e.g. ${tracked.slice(0, 3)}`,
  )
})

test('no wine points at a tracked image file that is an SVG', () => {
  const tracked = new Set(gitLsFiles('assets/img/wines').map((f) => f.split('/').pop()))
  const wines = JSON.parse(readFileSync('data/wines.json', 'utf8'))
  const bad = wines
    .map((w) => (w.imagePath || '').split('/').pop())
    .filter((f) => f.toLowerCase().endsWith('.svg') && tracked.has(f))
  assert.deepEqual(
    bad,
    [],
    'a wine points at a committed SVG — its placeholder should be generated by enrich, not stored',
  )
})
